#!/usr/bin/env ruby
require 'fileutils'
require 'logger'
require 'optparse'

require_relative "File.dirname(__FILE__)/../../lib/trustpair/challenge_runner"

options = {}
ARGV.options do |opts|
  opts.on('-d', '--data=val', String, 'data input file path') { |val| options[:data] = val }
  opts.on('--debug', 'for verbose run') { options[:log_level] = Logger::DEBUG }
  opts.parse!
end

@log = Logger.new(STDOUT)
@log.level = options[:log_level] || Logger::INFO

def self.export_companies(output)
  @log.debug "exporting companies: #{output}"
  export_path = Dir.pwd.to_s + '/../../../output'
  FileUtils.mkpath export_path
  File.open("#{export_path}/output.json", "w") do |f|
    f.write(output.to_json)
  end
end

challenge = Trustpair::ChallengeRunner.new(nil, @log)
data_path = options[:data] || File.dirname(__FILE__) + '/../data/data.csv'
companies = challenge.run(data_path)
export_companies(companies)


